#!/usr/bin/env python3
"""
generate_compose.py
Generates docker-compose.yml and docker-compose.override.yml
based on middleware.config.json.

Usage:
    python templates/scripts/generate_compose.py --config middleware.config.json
"""

import argparse
import json
import os
import sys


def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        print(f"[ERROR] Config file not found: {config_path}")
        sys.exit(1)
    with open(config_path) as f:
        return json.load(f)


def validate_config(config: dict):
    required = ["project_name", "services", "python_version"]
    missing = [k for k in required if k not in config]
    if missing:
        print(f"[ERROR] Missing required config keys: {missing}")
        sys.exit(1)


def base_compose(config: dict) -> str:
    """Generate production-safe docker-compose.yml."""
    project = config["project_name"]
    services = config.get("services", [])
    cronjobs = config.get("cronjobs", False)

    lines = []
    lines.append(f"# docker-compose.yml — production base")
    lines.append(f"# Project: {project}")
    lines.append(f"# Generated by generate_compose.py — do not edit manually\n")
    lines.append("services:")

    # web
    lines += _app_service("web", "web")

    # worker
    lines += _app_service("worker", "worker", depends_on=["db", "redis"])

    # beat
    lines += _app_service("beat", "beat", depends_on=["db", "redis"])

    # cron (only if cronjobs enabled)
    if cronjobs:
        lines += _app_service("cron", "cron", depends_on=["db", "redis"])

    # db
    lines.append("  db:")
    lines.append("    image: postgres:15-alpine")
    lines.append("    restart: unless-stopped")
    lines.append("    environment:")
    lines.append("      POSTGRES_DB: ${POSTGRES_DB:-app}")
    lines.append("      POSTGRES_USER: ${POSTGRES_USER:-app}")
    lines.append("      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}")
    lines.append("    volumes:")
    lines.append("      - postgres_data:/var/lib/postgresql/data")
    lines.append("    healthcheck:")
    lines.append("      test: [\"CMD-SHELL\", \"pg_isready -U ${POSTGRES_USER:-app}\"]")
    lines.append("      interval: 10s")
    lines.append("      timeout: 5s")
    lines.append("      retries: 5")
    lines.append("")

    # redis
    lines.append("  redis:")
    lines.append("    image: redis:7-alpine")
    lines.append("    restart: unless-stopped")
    lines.append("    healthcheck:")
    lines.append("      test: [\"CMD\", \"redis-cli\", \"ping\"]")
    lines.append("      interval: 10s")
    lines.append("      timeout: 5s")
    lines.append("      retries: 5")
    lines.append("")

    # elasticsearch (if declared)
    if "elasticsearch" in services:
        lines.append("  elasticsearch:")
        lines.append("    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0")
        lines.append("    restart: unless-stopped")
        lines.append("    environment:")
        lines.append("      - discovery.type=single-node")
        lines.append("      - xpack.security.enabled=false")
        lines.append("      - ES_JAVA_OPTS=-Xms512m -Xmx512m")
        lines.append("    volumes:")
        lines.append("      - es_data:/usr/share/elasticsearch/data")
        lines.append("    healthcheck:")
        lines.append("      test: [\"CMD-SHELL\", \"curl -s http://localhost:9200/_cluster/health | grep -q green\"]")
        lines.append("      interval: 20s")
        lines.append("      timeout: 10s")
        lines.append("      retries: 5")
        lines.append("")

    # sftp (if declared)
    if "sftp" in services:
        lines.append("  sftp:")
        lines.append("    image: atmoz/sftp:latest")
        lines.append("    restart: unless-stopped")
        lines.append("    environment:")
        lines.append("      SFTP_USERS: ${SFTP_USER:-user}:${SFTP_PASSWORD:-password}:1001")
        lines.append("    volumes:")
        lines.append("      - sftp_data:/home/${SFTP_USER:-user}/upload")
        lines.append("")

    # callcenter → external, no container

    # volumes
    lines.append("volumes:")
    lines.append("  postgres_data:")
    lines.append("  redis_data:")
    if "elasticsearch" in services:
        lines.append("  es_data:")
    if "sftp" in services:
        lines.append("  sftp_data:")

    return "\n".join(lines)


def _app_service(name: str, mode: str, depends_on: list = None) -> list:
    depends = depends_on or ["db", "redis"]
    lines = []
    lines.append(f"  {name}:")
    lines.append(f"    build: .")
    lines.append(f"    restart: unless-stopped")
    lines.append(f"    env_file: .env")
    lines.append(f"    environment:")
    lines.append(f"      APP_MODE: {mode}")
    lines.append(f"    depends_on:")
    for dep in depends:
        lines.append(f"      {dep}:")
        lines.append(f"        condition: service_healthy")
    lines.append("")
    return lines


def override_compose(config: dict) -> str:
    """Generate docker-compose.override.yml for local dev."""
    lines = []
    lines.append("# docker-compose.override.yml — local dev only")
    lines.append("# Automatically merged by docker compose up\n")
    lines.append("services:")

    lines.append("  web:")
    lines.append("    volumes:")
    lines.append("      - .:/app")
    lines.append("    ports:")
    lines.append("      - \"8000:8000\"")
    lines.append("    environment:")
    lines.append("      DEBUG: \"True\"")
    lines.append("      APP_MODE: web")
    lines.append("")

    lines.append("  worker:")
    lines.append("    volumes:")
    lines.append("      - .:/app")
    lines.append("    environment:")
    lines.append("      DEBUG: \"True\"")
    lines.append("")

    lines.append("  db:")
    lines.append("    ports:")
    lines.append("      - \"5432:5432\"")
    lines.append("")

    lines.append("  redis:")
    lines.append("    ports:")
    lines.append("      - \"6379:6379\"")

    return "\n".join(lines)


def generate(config: dict, base_output: str = "docker-compose.yml", override_output: str = "docker-compose.override.yml"):
    base_content = base_compose(config)
    override_content = override_compose(config)

    with open(base_output, "w") as f:
        f.write(base_content)
    print(f"[generate_compose] Written: {base_output}")

    with open(override_output, "w") as f:
        f.write(override_content)
    print(f"[generate_compose] Written: {override_output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate docker-compose files from middleware.config.json")
    parser.add_argument("--config", default="middleware.config.json", help="Path to middleware.config.json")
    parser.add_argument("--base-output", default="docker-compose.yml", help="Output path for docker-compose.yml")
    parser.add_argument("--override-output", default="docker-compose.override.yml", help="Output path for override file")
    args = parser.parse_args()

    config = load_config(args.config)
    validate_config(config)
    generate(config, base_output=args.base_output, override_output=args.override_output)
